server:
  address: ":8080"

backends:
  - "http://localhost:9001"
  - "http://localhost:9002"
  - "http://localhost:9003"

interval:
  "5"

db:
  address: "localhost:6379"

maxTokens:
  "5"

rate:
  "1"

salt:
 "secret key"